# Local development override - mounts source code for fast iteration
version: "3.8"

services:
  backend:
    image: ffball-backend:latest
    volumes:
      - ./backend:/app
      - /app/target # Exclude target directory for faster builds
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    ports:
      - "8080:8080"
    command: ["sh", "-c", "cd /app && cargo run"]

  frontend:
    image: ffball-frontend:latest
    volumes:
      - ./frontend:/app
      - /app/node_modules # Exclude node_modules for faster builds
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "cd /app && npm run dev"]
