# Local development override - mounts source code for fast iteration
services:
  backend:
    image: ffball-backend:latest
    volumes:
      - ./backend:/app
      - /app/target # Exclude target directory for faster builds
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - PATH=/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - "8080:8080"
    command:
      ["sh", "-c", "cd /app && /nix/var/nix/profiles/default/bin/cargo run"]

  frontend:
    image: ffball-frontend:latest
    volumes:
      - ./frontend:/app
      - /app/node_modules # Exclude node_modules for faster builds
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PATH=/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      ["sh", "-c", "cd /app && /nix/var/nix/profiles/default/bin/npm run dev"]
