version: '3.8'

# Development overrides for local development
# This file is automatically loaded by docker-compose
# Use: docker-compose up to run with development settings

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ffball_dev
      - POSTGRES_USER=ffball_dev
      - POSTGRES_PASSWORD=ffball_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/src/scripts:/docker-entrypoint-initdb.d/

  backend:
    environment:
      - DATABASE_URL=postgres://ffball_dev:ffball_dev@postgres:5432/ffball_dev
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/target:/app/target
      - cargo_cache:/usr/local/cargo/registry
    command: cargo watch -x run

  frontend:
    ports:
      - "3000:3000"
      - "5173:5173"  # Vite dev server
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/static:/app/static:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/svelte.config.js:/app/svelte.config.js:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

  # Development tools
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

volumes:
  postgres_dev_data:
  cargo_cache:
  node_modules: