[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
headless_chrome = "1.0.13"
playwright = "0.0.20"
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper = "0.20.0"
select = "0.6.0"
serde_json = "1.0.125"
sxd-xpath = "0.4.2"
tokio = { version = "1.39.2", features = ["full"] }
xmltree = "0.10.3"
